/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { type Mesh, MeshPhysicalMaterial } from "three";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { type ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Title: Mesh;
  };
};

// Metallic material for the title text.
const titleMaterial = new MeshPhysicalMaterial({
  color: "#ffffff",
  metalness: 1,
  roughness: 0,
});

/**
 * The 3D Odyssey title text.
 */
export function Title(props: ThreeElements["group"]) {
  const { nodes } = useGLTF("/Title.glb") as unknown as GLTFResult;
  return (
    <group {...props} rotation={[-Math.PI / 2, 0, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Title.geometry}
        material={titleMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Title.glb");
